Bug 1625965 - Raptor Youtube-Playback Fenix tests are silently failin…
mozilla/perf-youtube-playback pull request #16
Opened 2020-04-03 08:19 UTC by bebef1987

…g on VP9

2020-04-03 11:24 UTC, whimboo requested changes
Can you please explain why those changes are necessary?

2020-04-03 11:24 UTC, whimboo commented on 2019/harness/test.js
> +                fail: test.prototype.failures,
Should whether be `pass` or `failures`.

2020-04-06 13:53 UTC, bebef1987 commented on 2019/harness/test.js
> +                fail: test.prototype.failures,
Used `fail`

2020-04-06 13:55 UTC, gmierz commented on 2019/media/playbackperfTest.js
> +          runner.checkLE(totalDroppedFrames, 1,);
Missing `'Total dropped frames'` as the last parameter.

2020-04-06 14:20 UTC, gmierz approved these changes
This looks good to me, thanks!

2020-04-07 07:37 UTC, whimboo approved these changes

2020-04-07 07:37 UTC, whimboo commented
Given that Greg is fine with those changes lets get it merged.

2020-04-07 07:37 UTC, merged

2020-04-17 06:56 UTC, whimboo commented
@marianrai does our dev server for the 2020 work already got this change?